### ISSUE TITLE
Add config for custom tokenlist [APE-1534]

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape-tokens#36]
### Overview

Add config item for `tokens` that supports an ad-hoc list of custom tokens for a project to use (or a global custom list)

### Specification

Using the [`TokenInfo`](https://github.com/ApeWorX/py-tokenlists/blob/main/tokenlists/typing.py#L33) type from `py-tokenlists`:

```yaml
tokens:
- name: "cHaOSneT Credits"
  address: 0x0579fc0e764e7cc10c7175533b1330b184b8d505
  symbol: CHAOS
  decimals: 18
  chainId: 11155111
- ... # More tokens
```

Also, merge the global list (under `~/.ape/ape-config.yaml`) with a local project's

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.
