### ISSUE TITLE
Allow configuring tokenlists needed for project

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape-tokens#47]
### Overview

Especially in a silverback context, it is very useful to be able to describe tokenlists that should be used with the project

Not sure if they should automatically install, but an easy way to install them would be good. In the silverback build context, it could run `RUN ape tokens install .` as a build step if the config is detected

### Specification

```yaml
tokens:
  tokenlists:
  - name: CoinGecko
    url: https://tokens.coingecko.com/uniswap/all.json
```

And install with `ape tokens install .` (not sure if we can "extend" the cli from `py-tokenlists` with this command)

### Dependencies
n/a
